name: ArmorStandAdjustor
author: petomka
version: ${project.version}
main: me.petomka.armorstandeditor.Main

api-version: 1.13

commands:
  armorstandeditor:
    aliases: ['aes', 'as', 'aedit', 'armorstandadjustor', 'asa']