name: ArmorStandAdjustor
author: petomka
version: ${project.version}
main: me.petomka.armorstandeditor.Main
website: https://www.spigotmc.org/resources/armor-stand-adjustor.63811/

api-version: "1.13"

commands:
  armorstandeditor:
    aliases: ['aes', 'as', 'aedit', 'armorstandadjustor', 'asa']